### ISSUE TITLE
Error with installation

### ISSUE THREAD

**Issue by barrro12** [GA-MO/new-react-app#1]
I am trying to install react from the instructions.  All is fine until I get to run npm start.
after fixing symlink for node with /new-react-app/node_modules/webpack-log/index.js
my output suggests an error in installed code viz:

~/new-react-app$ npm start

> new-react-app@1.0.0 start /home/robin/new-react-app
> webpack-dev-server

/home/robin/new-react-app/node_modules/webpack-log/index.js:29
  const { id } = options;
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/robin/new-react-app/node_modules/webpack-dev-server/lib/createLog.js:3:16)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

npm ERR! Linux 4.10.0-28-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! new-react-app@1.0.0 start: `webpack-dev-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the new-react-app@1.0.0 start script 'webpack-dev-server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the new-react-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs new-react-app
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls new-react-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/robin/new-react-app/npm-debug.log

**Comment by GA-MO** [comment]
@barrro12 
Did you install `new-react-app` in the global ?
Try update node.js
